//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingAccountRole
    {
        public int PartyId { get; set; }
        public int BillingAccountId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual BillingAccount BillingAccount { get; set; }
        public virtual Party Party { get; set; }
    }
}
