//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMechanism
    {
        public ContactMechanism()
        {
            this.PartyContactMechanism = new HashSet<PartyContactMechanism>();
        }
    
        public int Id { get; set; }
    
        public virtual EmailAddress EmailAddress { get; set; }
        public virtual ICollection<PartyContactMechanism> PartyContactMechanism { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual PostalAddress PostalAddress { get; set; }
    }
}
