//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRoleType
    {
        public InvoiceRoleType()
        {
            this.InvoiceRoles = new HashSet<InvoiceRole>();
        }
    
        public int RoleTypeId { get; set; }
    
        public virtual ICollection<InvoiceRole> InvoiceRoles { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
