//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRole
    {
        public int PartyId { get; set; }
        public int InvoiceId { get; set; }
        public int RoleTypeId { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual InvoiceRoleType InvoiceRoleType { get; set; }
        public virtual Party Party { get; set; }
    }
}
