//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.InvoiceRoles = new HashSet<InvoiceRole>();
            this.InvoiceTerms = new HashSet<InvoiceTerm>();
        }
    
        public int Id { get; set; }
        public int PartyId { get; set; }
        public int RoleTypeId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual RoleType RoleType { get; set; }
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        public virtual ICollection<InvoiceRole> InvoiceRoles { get; set; }
        public virtual InvoiceStatu InvoiceStatu { get; set; }
        public virtual ICollection<InvoiceTerm> InvoiceTerms { get; set; }
    }
}
