//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
