//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Invoices = new HashSet<Invoice>();
            this.InvoiceRoles = new HashSet<InvoiceRole>();
            this.Payments = new HashSet<Payment>();
            this.Payments1 = new HashSet<Payment>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
        public virtual RoleType RoleType { get; set; }
        public virtual ICollection<InvoiceRole> InvoiceRoles { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Payment> Payments1 { get; set; }
    }
}
