//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int PaymentMethodTypeId { get; set; }
        public int PartyIdFrom { get; set; }
        public int PartyIdTo { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public decimal Amount { get; set; }
        public int Currency { get; set; }
        public string Comment { get; set; }
        public int PaymentTypeId { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual Party Party1 { get; set; }
        public virtual PaymentMethodType PaymentMethodType { get; set; }
    }
}
