//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayBook.DataAccess.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleType
    {
        public RoleType()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Parties = new HashSet<Party>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual InvoiceRoleType InvoiceRoleType { get; set; }
        public virtual ICollection<Party> Parties { get; set; }
    }
}
